config/routes.rb
Rails.application.routes.draw do
        root 'lists#new'
        get'lists/new'=>'lists#new',as: 'new_list'
        post'lists'=>'lists#create',as: 'create_list'
        get'lists'=>'lists#index',as: 'list'
        get'lists/:id'=>'lists#show',as: 'show_list'
        get 'lists/:id/edit'=>'lists#edit',as: 'edit_list'
        patch'lists/:id'=>'lists#update',as: 'update_list'
        delete'lists/:id'=>'lists#destroy',as: 'destroy_list'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
    has_one_attached :image
    
    validates:title,presence:true
    validates:body,presence:true
    validates:image,presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def new
    @list=List.new
  end
  
  def create
    @list=List.new(list_params)
      if @list.save
        flash[:notice]="success"
        redirect_to list_path
      else
        render :new
      end
  end

  def index
    @lists=List.all
  end

  def show
    @list=List.find(params[:id])
  end

  def edit
    @list=List.find(params[:id])
  end
  
  def update
    @list=List.find(params[:id])
      if @list.update(list_params)
        flash[:notice]="success"
        redirect_to list_path
      else
        render :edit
      end
  end
  
  def destroy
    list=List.find(params[:id])
    list.destroy
    redirect_to list_path
  end
  
  private
  def list_params
    params.require(:list).permit(:title,:body,:image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sample</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <% if flash[:notice]%>
    <p class="notice notice-success">
        <%= flash[:notice]%>
    </p>
<%end%>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<h1>edit</h1>

<% if @list.errors.any? %>
  <%= @list.errors.count %>件のエラー
  <ul>
    <% @list.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%=form_with model: @list,url: update_list_path(@list.id),method: :patch,local:true do|f|%>

<%=f.label:title%><br>
<%=f.text_field:title%><br>
<%=f.label:body%><br>
<%=f.text_area:body%><br>
<%=f.label:image%><br>
<%=f.file_field:image%><br>
<%=f.submit'complate'%>
<%end%>

app/views/lists/index.html.erb
<h1>all</h1>

<%@lists.each do|list|%>

<h4>title</h4>

<%=link_to list.title,show_list_path(list.id) %>

<h4>phpto</h4>
 <%if list.image.attached?%>
    <%=image_tag list.image,size: "200x200"%>
 <%else%>
     <%=image_tag 'no_image',size: "200x200"%>
 <%end%>
<%end%>

app/views/lists/new.html.erb
<h1>new</h1>

<% if @list.errors.any? %>
  <%= @list.errors.count %>件のエラー
  <ul>
    <% @list.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%=form_with model: @list,url: create_list_path,method: :post,local:true do |f|%>

<%=f.label:title%><br>
<%=f.text_field:title%><br>

<%=f.label:body%><br>
<%=f.text_area:body%><br>

<%=f.label:image%><br>
<%=f.file_field:image%><br>
<%=%>

<%=f.submit'ok'%>

<%end%>

app/views/lists/show.html.erb
<h2>title</h2>
<%=@list.title%>

<h2>text</h2>
<%=@list.body%><br>

<h2>phpto</h2>
    <%if @list.image.attached?%>
        <%=image_tag @list.image,size: "300x300"%>
    <%else%>
        <%=image_tag 'no_image',size: "300x300"%>
    <%end%><br>

<%=link_to 'edit',edit_list_path(@list.id)%>
<%=link_to 'delete',destroy_list_path(@list.id),method: :delete,'data-confirm'=>'really?'%>